# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Var1SErckVaP8vCAoCO5yjIc0pA-S-Uu
"""

!pip install -q transformers torch scikit-learn pandas matplotlib seaborn

import torch
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from transformers import AutoTokenizer, AutoModel
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print("Using device:", device)

sentences = [
    "I love playing football.",
    "I enjoy playing soccer.",
    "The weather is very hot.",
    "It is a sunny day.",
    "I like eating pizza.",
    "Pizza is my favorite food."
]

for i, sentence in enumerate(sentences, start=1):
    print(f"S{i}: {sentence}")

bert_name = "bert-base-uncased"

bert_tokenizer = AutoTokenizer.from_pretrained(bert_name)
bert_model = AutoModel.from_pretrained(bert_name)

bert_model = bert_model.to(device)
bert_model.eval()

print("BERT model loaded successfully")

gpt_name = "gpt2"

gpt_tokenizer = AutoTokenizer.from_pretrained(gpt_name)
gpt_model = AutoModel.from_pretrained(gpt_name)

# GPT-2 does not have a separate padding token
gpt_tokenizer.pad_token = gpt_tokenizer.eos_token
gpt_model.config.pad_token_id = gpt_tokenizer.pad_token_id

gpt_model = gpt_model.to(device)
gpt_model.eval()

print("GPT model loaded successfully")

gpt_name = "gpt2"

gpt_tokenizer = AutoTokenizer.from_pretrained(gpt_name)
gpt_model = AutoModel.from_pretrained(gpt_name)

# GPT-2 does not have a separate padding token
gpt_tokenizer.pad_token = gpt_tokenizer.eos_token
gpt_model.config.pad_token_id = gpt_tokenizer.pad_token_id

gpt_model = gpt_model.to(device)
gpt_model.eval()

print("GPT model loaded successfully")

def generate_embeddings(sentences, tokenizer, model):
    # Convert sentences into tokens
    inputs = tokenizer(
        sentences,
        padding=True,
        truncation=True,
        max_length=128,
        return_tensors="pt"
    )

    inputs = {
        key: value.to(device)
        for key, value in inputs.items()
    }

    # Generate hidden representations
    with torch.no_grad():
        outputs = model(**inputs)

    token_embeddings = outputs.last_hidden_state

    # Mean pooling
    attention_mask = inputs["attention_mask"].unsqueeze(-1)

    masked_embeddings = token_embeddings * attention_mask

    summed_embeddings = masked_embeddings.sum(dim=1)

    token_counts = attention_mask.sum(dim=1)

    sentence_embeddings = summed_embeddings / token_counts

    return sentence_embeddings.cpu().numpy()


# Generate BERT embeddings
bert_embeddings = generate_embeddings(
    sentences,
    bert_tokenizer,
    bert_model
)

# Generate GPT embeddings
gpt_embeddings = generate_embeddings(
    sentences,
    gpt_tokenizer,
    gpt_model
)

print("BERT embedding shape:", bert_embeddings.shape)
print("GPT embedding shape:", gpt_embeddings.shape)

# Calculate cosine similarity
bert_similarity = cosine_similarity(bert_embeddings)
gpt_similarity = cosine_similarity(gpt_embeddings)

# Display BERT similarity matrix
print("BERT Similarity Matrix")
display(pd.DataFrame(
    bert_similarity,
    index=[f"S{i+1}" for i in range(6)],
    columns=[f"S{i+1}" for i in range(6)]
).round(3))

# Display GPT similarity matrix
print("GPT Similarity Matrix")
display(pd.DataFrame(
    gpt_similarity,
    index=[f"S{i+1}" for i in range(6)],
    columns=[f"S{i+1}" for i in range(6)]
).round(3))

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

sns.heatmap(
    bert_similarity,
    annot=True,
    cmap="Blues",
    xticklabels=[f"S{i+1}" for i in range(6)],
    yticklabels=[f"S{i+1}" for i in range(6)],
    ax=axes[0]
)

axes[0].set_title("BERT Similarity")

sns.heatmap(
    gpt_similarity,
    annot=True,
    cmap="Greens",
    xticklabels=[f"S{i+1}" for i in range(6)],
    yticklabels=[f"S{i+1}" for i in range(6)],
    ax=axes[1]
)

axes[1].set_title("GPT Similarity")

plt.tight_layout()
plt.show()

# Apply K-Means to BERT embeddings
bert_kmeans = KMeans(
    n_clusters=3,
    random_state=42,
    n_init=10
)

bert_clusters = bert_kmeans.fit_predict(bert_embeddings)


# Apply K-Means to GPT embeddings
gpt_kmeans = KMeans(
    n_clusters=3,
    random_state=42,
    n_init=10
)

gpt_clusters = gpt_kmeans.fit_predict(gpt_embeddings)


# Display clustering results
results = pd.DataFrame({
    "Sentence": sentences,
    "BERT Cluster": bert_clusters,
    "GPT Cluster": gpt_clusters
})

display(results)

# Reduce BERT embeddings to 2 dimensions
bert_pca = PCA(n_components=2)
bert_2d = bert_pca.fit_transform(bert_embeddings)

# Reduce GPT embeddings to 2 dimensions
gpt_pca = PCA(n_components=2)
gpt_2d = gpt_pca.fit_transform(gpt_embeddings)


# Create two scatter plots
fig, axes = plt.subplots(1, 2, figsize=(14, 6))

axes[0].scatter(
    bert_2d[:, 0],
    bert_2d[:, 1],
    c=bert_clusters,
    cmap="viridis",
    s=150
)

for i, sentence in enumerate(sentences):
    axes[0].annotate(
        f"S{i+1}",
        (bert_2d[i, 0], bert_2d[i, 1])
    )

axes[0].set_title("BERT Clustering")
axes[0].set_xlabel("PCA Component 1")
axes[0].set_ylabel("PCA Component 2")


axes[1].scatter(
    gpt_2d[:, 0],
    gpt_2d[:, 1],
    c=gpt_clusters,
    cmap="viridis",
    s=150
)

for i, sentence in enumerate(sentences):
    axes[1].annotate(
        f"S{i+1}",
        (gpt_2d[i, 0], gpt_2d[i, 1])
    )

axes[1].set_title("GPT Clustering")
axes[1].set_xlabel("PCA Component 1")
axes[1].set_ylabel("PCA Component 2")

plt.tight_layout()
plt.show()

pairs = [
    (0, 1),
    (2, 3),
    (4, 5)
]

comparison = []

for i, j in pairs:
    comparison.append({
        "Sentence Pair": f"S{i+1} and S{j+1}",
        "BERT Similarity": bert_similarity[i, j],
        "GPT Similarity": gpt_similarity[i, j]
    })

comparison_df = pd.DataFrame(comparison)

display(comparison_df.round(3))